apiVersion: v1
kind: Service
metadata:
  name: razarion-server-service
spec:
  type: LoadBalancer
  selector:
    app: razarion-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080