apiVersion: v1
kind: Service
metadata:
  name: razarion-server-service
  annotations:
    cloud.google.com/backend-config: '{"default": "razarion-cdn-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: razarion-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
